"""tasks add foreign key name

Revision ID: 14ee8a7c8d23
Revises: 6801b9160add
Create Date: 2024-04-23 21:09:53.388432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ee8a7c8d23'
down_revision = '6801b9160add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key('fk_task_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_user_id', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
