"""tasks

Revision ID: 6801b9160add
Revises: 99f9c0279832
Create Date: 2024-04-23 20:59:04.102559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6801b9160add'
down_revision = '99f9c0279832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
